apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: {{ include "size-exporter.name" . }}
    component: size-exporter
    helm.sh/chart: {{ include "size-exporter.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ include "size-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
